name: Create Release with Zipped Folder

on:
  push:
    branches:
      - main
      - ask.hass-2024.1-enum-hacs

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get version
        id: extract_version
        run: echo "::set-output name=version::$(jq -r '.version' custom_components/htd_mc/manifest.json)"

      - name: Package
        run: zip -r htd_mc.zip custom_components/htd_mc

      - name: Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: v${{ steps.extract_version.outputs.version }}
          tag_name: v${{ steps.extract_version.outputs.version }}          
          draft: true
          prerelease: true
          generate_release_notes: true
          file: htd_mc.zip
